#!/bin/sh
appname=`basename $0 | sed s,\.sh$,,`

exe_directory="././/lib/ser-player/"

export LD_LIBRARY_PATH=././/lib/
export QT_PLUGIN_PATH=$exe_directory/plugins/
#ldd $exe_directory/$appname "$@"  # Uncomment for debug
$exe_directory/$appname "$@"

